fix: change color behavior

diff --git a/scripts/lib/stdio b/scripts/lib/stdio
--- a/scripts/lib/stdio
+++ b/scripts/lib/stdio
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 function err {
-  echo "error: $@" 1>&2
+  echo "${Cred}error${Creset}: $@" 1>&2
 }
 
 function warn {
-  echo "warn: $@" 1>&2
+  echo "${Cyellow}warn${Creset}: $@" 1>&2
 }
